"""update auction table

Revision ID: 10c67ac19292
Revises: 1a592abde3a5
Create Date: 2022-09-24 16:06:54.465252

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '10c67ac19292'
down_revision = '1a592abde3a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AuctionBid',
    sa.Column('bid_id', sa.Integer(), nullable=False),
    sa.Column('auction_id', sa.Integer(), nullable=True),
    sa.Column('bid', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['auction_id'], ['Auction.auction_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('bid_id')
    )
    op.create_index(op.f('ix_AuctionBid_bid_id'), 'AuctionBid', ['bid_id'], unique=False)
    op.drop_constraint('Auction_highest_bid_user_id_fkey', 'Auction', type_='foreignkey')
    op.drop_column('Auction', 'highest_bid_user_id')
    op.drop_column('Auction', 'highest_bid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Auction', sa.Column('highest_bid', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('Auction', sa.Column('highest_bid_user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('Auction_highest_bid_user_id_fkey', 'Auction', 'User', ['highest_bid_user_id'], ['user_id'])
    op.drop_index(op.f('ix_AuctionBid_bid_id'), table_name='AuctionBid')
    op.drop_table('AuctionBid')
    # ### end Alembic commands ###
