"""update product table

Revision ID: 175f435b88ab
Revises: 695526d6eabd
Create Date: 2022-09-24 13:44:53.509597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '175f435b88ab'
down_revision = '695526d6eabd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Product',
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index(op.f('ix_Product_product_id'), 'Product', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Product_product_id'), table_name='Product')
    op.drop_table('Product')
    # ### end Alembic commands ###
