"""update auction table

Revision ID: 1a592abde3a5
Revises: f1bc92167a78
Create Date: 2022-09-24 15:38:31.157084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a592abde3a5'
down_revision = 'f1bc92167a78'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Auction', sa.Column('product_id', sa.String(), nullable=True))
    op.add_column('Auction', sa.Column('min_bid', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'Auction', 'Product', ['product_id'], ['product_id'])
    op.drop_constraint('Product_auction_id_fkey', 'Product', type_='foreignkey')
    op.drop_column('Product', 'auction_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Product', sa.Column('auction_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('Product_auction_id_fkey', 'Product', 'Auction', ['auction_id'], ['auction_id'])
    op.drop_constraint(None, 'Auction', type_='foreignkey')
    op.drop_column('Auction', 'min_bid')
    op.drop_column('Auction', 'product_id')
    # ### end Alembic commands ###
