"""modify table

Revision ID: 1aef6e7c440d
Revises: 10c67ac19292
Create Date: 2022-09-24 21:17:48.439874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aef6e7c440d'
down_revision = '10c67ac19292'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Auction', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Auction', 'name')
    # ### end Alembic commands ###
