"""modify table

Revision ID: 23a08a309721
Revises: 1aef6e7c440d
Create Date: 2022-09-24 22:14:26.814848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23a08a309721'
down_revision = '1aef6e7c440d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Auction', sa.Column('highest_bid', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Auction', 'highest_bid')
    # ### end Alembic commands ###
