"""adds product table

Revision ID: 64bb3c5e1ada
Revises: 6ddbf501685c
Create Date: 2022-09-24 13:31:54.841313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64bb3c5e1ada'
down_revision = '6ddbf501685c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
