"""update product table

Revision ID: 695526d6eabd
Revises: e93febee7b93
Create Date: 2022-09-24 13:43:11.510091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '695526d6eabd'
down_revision = 'e93febee7b93'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
