"""update product table

Revision ID: e93febee7b93
Revises: 64bb3c5e1ada
Create Date: 2022-09-24 13:38:59.339783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e93febee7b93'
down_revision = '64bb3c5e1ada'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
