"""update product table

Revision ID: f1bc92167a78
Revises: 175f435b88ab
Create Date: 2022-09-24 14:53:33.517940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1bc92167a78'
down_revision = '175f435b88ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Auction',
    sa.Column('auction_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('auction_status', sa.Enum('WAITING', 'ACTIVE', 'STOPPED', name='auctionstatus'), nullable=True),
    sa.Column('start_time', sa.Integer(), nullable=True),
    sa.Column('end_time', sa.Integer(), nullable=True),
    sa.Column('number_extensions', sa.Integer(), nullable=True),
    sa.Column('highest_bid', sa.Float(), nullable=True),
    sa.Column('highest_bid_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['highest_bid_user_id'], ['User.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('auction_id')
    )
    op.create_index(op.f('ix_Auction_auction_id'), 'Auction', ['auction_id'], unique=False)
    op.add_column('Product', sa.Column('auction_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Product', 'Auction', ['auction_id'], ['auction_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Product', type_='foreignkey')
    op.drop_column('Product', 'auction_id')
    op.drop_index(op.f('ix_Auction_auction_id'), table_name='Auction')
    op.drop_table('Auction')
    # ### end Alembic commands ###
